;
; Copyright (c) 2024 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;

; struct typedefs
; .. include_startingpoint_device_info_cddl_rst
; Device Info service request payload.
device_info_service_read_req = (
      2,
      target: uint, ; 0 - uuid, 1 - hw_version
)

device_info_service_write_req = (
      2,
      target: uint, ; 0 - uuid, 1 - hw_version
      data: tstr,
)

; Device Info service response to read data.
device_info_service_read_resp = (
      3,
      target: uint, ; 0 - uuid, 1 - hw_version
	status: uint, ; 0 - success, 0x1001001 - internal_error, 0x1001002 - unprogrammed
	data: tstr,
)

; Device Info service response to write payload.
device_info_service_write_resp = (
      3,
      target: uint, ; 0 - uuid, 1 - hw_version
	status: uint, ; 0 - success, 0x1001001 - internal_error, 0x1001002 - unprogrammed
)

device_info_req = [
      msg: (
            device_info_service_read_req /
            device_info_service_write_req
      ),
]

device_info_resp = [
      msg: (
            device_info_service_read_resp /
            device_info_service_write_resp
      ),
]

; .. include_startingpoint_device_info_cddl_rst
